# ,,,╓w╦▄▄▄▓████████▄
# ,,▄▄▄▄▄▄▄▓▓▓▓▓▓▓▓██████████████████,
# █████████████████▓▓▓▓██████████████████████████▓▄▄▄▄▄▄
# ▐████████████████▓▓▓▓█████████████████████████████████
# ███████████▓▓╢▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓███████████████████████
# ██████████▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓███▓▀▀▓▓▓▓╣▓██████████████╣@@H╗╗╓,,
# ▐█████████▓▓▓▓███▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒╬▓▓▓▓██████████████▓▓▓▓▒▒▒▒▒▒▒▒▒▓▓▓▓▄▄▄▄▄,,,
# █████████▓▓█████▓▓▓▓▓╢▓▓▓▓▓▒▒▒▒▒▒▓▓╫▓▓▓████████████▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▓▓▓▓▓▓████
# █████████▓▓████████▓▓▓▓▓▓▓▓▒▒▒▒▒▒▒▒▒▒▓▓▓▒▒▒▒▒▓▓▒▒▒▒▒▒▓▒▒▒▒▒▒▒▒▒▒▒▒▒╬▓▓▓▓▓█████
# ▐█████████▓█████████████▓▓▓▓▓▓▓▄▄▒▒▒▒▒▒╬▒▒▒▒▒▒╬▓▓▓╢▓▓▓▓▓▓╢▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓████▌
# ]█████████▓▓█████████▓██▓▓▓▓▓▓▓▓▓▓▓▓███▓██▓▓▓▓█████▓▓▓█▓▓▓▓▓▓▓▓▓▓▓╢▓▓▓███████▌
# █████████▓▓█████████████▓▓▓▓▓▓▓▓▓▓▓████████████████████▓▓▓▓▓▓▓▓▓▓▓▓█████████
# ▀████████▓▓███████████████████████████▓██████████████▓███████▓▓▓▓▓▓█▓███████
# ▐█████████▓██████████▓▓▓▓▓███████████████████████████████████▓▓▓▓╢▓▓▓███████
# █████████▓███████▓██▓▓▓▓▓▓▓▓▓▓███████████████████████████▓▓╣▓▓▓▓▓▓▓███████▌
# █████████▓▓████████████▓▓▓▓▓▓▓▓██████████████████████▓▓▓▓▓▓▓▓▓▓▓▓█████████▌
# ▐████████▌▓█████████████████▓▓▓█▓████████████████████▓▓▓▓▓████▓▓▓████▓████
# ████████▌▓███████████████████████████████████████████████████▓▓▓▓▓▓▓▓▓███
# █████████▓█████████████▓▓▓▓▓▓█████████████████████████████▓▓▓▓▓▓▓▓███████
# ▐████████▓▓███████████▓▓▓▓▓▓▓▓█▓███████████████████████▓▓▓▓▓▓▓▓▓████████▌
# ████████▓▓██████████████▓▓▓▓▓████████████████████▓████▓▓▓▓▓▓▓▓████▓████M
# █████████▓███████▓████▓███████████▓██████████████████████▓▓▓▓▓▓▓▓▓▓████
# ▐████████▓█████████▓▓▓▓▓▓▓▓█████████████████████████████▓▓╢▓▓▓▓▓▓██████
# ¬████████▓▓██████████▓▓▓▓▓▓▓▓▓████████████████████████▓▓▓▓▓▓▓▓█████████
# ████████▌▓███████████████▓▓▓▓█████▓██████████████▓▓▓▓▓▓▓▓█▓▓▓█▓▓▓▓███▌
# ▀███████▌▓██████████████████████▓█████████████████▓▓██████▓▓╢▓▓▓▓████M
# ▐████████▓████████████▓▓▓▓▓████████████████████████████▓▓▓▓▓▓▓███████
# ████████▓▓███████████▓▓▓▓▓▓▓▓███████████████████████▓▓▓▓▓▓▓█████▓██▀
# ████████▓▓███████████▓██▓▓▓▓▓▓▓██▓█████████████████▓▓▓▓▓▓▓▓▓▓▓██▀`
# ▐████████▓▓▓██████▓▓▓▓▓████▓████▓█▓███████████████████▓▓▓╢▓▓▓█`
# ████████▓▓▓██▓████▓▓▓▓▓▓▓▓▓█████████████████████████▓╢▓▓▓▓███
# ████████▓▓▓▓▓▓▓██████▓▓▓▓▓▓█▓███████████████████▓▓▓▓▓╢▓▓▓▓██▌
# ▐███████▓▓▓▓▓▓▓▓███████▓▓▓▓█▓██████████████████▓▓▓▓▓▓▓▓▓████▌
# ████████▓▓▓▓█▓▓████████▓▓▓▓▓▓█████████████████▓▓╢▓╢▓▓██████
# ████████▓▓▓███████████████▓▓▓▓███████████████▓▓▓▓██▓▓▓▓████
# ▐███████▓▓▓▓▓▓████████▓███████████████████████████▓╢▓▓█████
# ¬███████▌▓▓███▓████████▓▓▓▓▓▓███████████████████▓▓╣▓███████
# ████████▓▓▓█▓▓▓█████████▓▓▓▓▓▓▓█████████████▓▓▓▓▓███▓▓███▌
# ▀███████▓▓▓▓█████████▓█▓██████▓▓████████████▓██▓▓▓╣▓▓████▌
# ▐███████▓█████████████▓▓▓▓▓███████████████████▓╢▓▓▓██████
# █████████████████████████▓▓▓▓██████████████▓▓▓▓█▓▓▓▓████
# ███████▓▓▓▓▓▓▓███████▓█████▓█▓███████████▓█▓███▓▓▓▓███████▄,
# ▐██████▓▓▓█▓▓▓▓▓██████▓▓▓▓▓██████████████████▓╣▓▓████▓▓██████
# ▀▀███████▓▓▓▓▓▓▓▓▓▓█████▓▓▓▓██████████████▓▓▓▓██▓▓▓▓▓▓█████▌
# ╙▀████████▓▓▓▓▓▓▓▓▓███████████████████▓████▓▓▓▓▓▓▓▓█████═
# -▀███████▓▓▓▓▓▓▓▓▓▓▓██████████████████▓▓▓▓▓▓▓▓█████▀
# ▀████████▓█▓▓█▓▓▓▓▓█████████████▓▓▓▓▓▓▓▓▓▓███`
# ▀▀████████▓▓▓▓▓▓▓▓▓▓██████▓▓▓▓▓▓█▓▓▓▓██▀
# ▀████████▓▓▓▓▓▓▓▓▓▓█▓▓▓▓▓▓▓▓██▓██▀
# ▀█████████▓█████▓███████████▀
# ▀██████████████████████▀
# ╙▀███████████████▀
# ▀██████████▀
# ▀█████▀

#===========================
# Kebab - An Uroria project
#===========================

# ServerSocket configuration:
# You can override both with these command arguments:
# - Host: "-Dserver.host="0.0.0.0"
# - Port: "-Dserver.port=25565"
[server]
host="0.0.0.0"
port=25565

# Client-Rendering:
# Can impact client and server performance.
# Simulation distance 1 below view distance is recommend.
[rendering]
viewdistance=6
simulationdistance=5

# Scheduler configuration:
# TPS defines how often chunk rendering and it's entities should be updated per second.
# TPS higher than 20 is not recommend.
# CorePoolSize at 0 is fine. Don't change it if you don't know what you're doing!
[scheduler]
tps=20
corepoolsize=0